export enum PARTICIPANT {
  ADAM = "*Adam",
  ALBERT = "*Albert",
  ALICJA = "Alicja",
  ANGELA = "*Angela",
  BARTEK = "*Bartek",
  DAMIAN = "Damian",
  DOMCIA = "*Domcia",
  ELA = "*Ela",
  GENIU = "Geniu",
  GOSIA = "*Gosia",
  JOLA_K = "*Jola K.",
  JOLA_P = "Jola P.",
  KASIA = "*Kasia",
  KRZYSIU = "*Krzysiu",
  MAGDA = "Magda",
  MARCIN_P = "*Marcin P.",
  MARCIN_Z = "Marcin Ż.",
  MARTA = "Marta",
  MICHAL = "Michał",
  RYSIU = "*Rysiu",
  TOMEK = "Tomek",
}
