export enum TEAM {
  ALB = "Albania",
  AUT = "Austria",
  BEL = "Belgia",
  CHE = "Szwajcaria",
  CZE = "Czechy",
  DEU = "Niemcy",
  DNK = "Dania",
  ENG = "Anglia",
  ESP = "Hiszpania",
  FRA = "Francja",
  GEO = "Gruzja",
  HRV = "Chorwacja",
  HUN = "Węgry",
  ITA = "Włochy",
  NLD = "Holandia",
  POL = "Polska",
  POR = "Portugalia",
  ROU = "Rumunia",
  SCO = "Szkocja",
  SRB = "Serbia",
  SVK = "Słowacja",
  SVN = "Słowenia",
  TUR = "Turcja",
  UKR = "Ukraina",
  TBD = "-",
}
